import json , os
import certifi     #It verify the identity of your website
from pymongo import MongoClient
from datetime import datetime , timezone
from bson.objectid import ObjectId   #(bson) is a mongoDB library used to covert IDS into special format
from flask_cors import CORS   # It stops security when separate from frontend and we try to visit backend
from flask import Flask, render_template, request, jsonify    
# from sql_connection import get_connection  # It is initialize and manage your SQL connection

app = Flask(__name__)
CORS(app)
date = datetime.now(timezone.utc)

todos = []

# Replace your current MongoClient line with this exact block
myclient = MongoClient(
    'mongodb://rupalij_db_user:rupali2026@ac-cpcdrqx-shard-00-00.81fdwl0.mongodb.net:27017,ac-cpcdrqx-shard-00-01.81fdwl0.mongodb.net:27017,ac-cpcdrqx-shard-00-02.81fdwl0.mongodb.net:27017/Todo_db?ssl=true&replicaSet=atlas-m1u6w6-shard-0&authSource=admin&retryWrites=true&w=majority',
    tls=True,
    tlsAllowInvalidCertificates=True
)
   #It tells database where to find security certificate on your computer

mydb = myclient['Todo_db']  #create DB
mycol = mydb['Todos']  #create collection


@app.route("/")
def home():
    return render_template('index.html')

@app.route("/about/")
def about():
    return render_template('about.html')

# TO ADD DATA
@app.route('/todo', methods=['POST'])
def data():
    request_data = request.get_json()

    if not request_data:
        return jsonify({"status": "error", "message": "No JSON data received"}), 400

    try:    
       
        title = request_data.get('title')
        desc = request_data.get('desc')
        Date = date

        result = mycol.insert_one({'Title':title , 'Description':desc , 'Date':date})

        inserted_id = str(result.inserted_id)   # It converts IDS generated by MongoDB into Text String
    
        return jsonify({
            "status": "success", 
            "message": "Todo added successfully!",
            "id": inserted_id 
        }), 201
            
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

# TO DELETE DATA

@app.route('/todo/<todo_id>', methods=['DELETE'])
def delete_todo(todo_id):
    
    try:
        
        result = mycol.delete_one({'_id':ObjectId(todo_id)})
           
        return jsonify({"status": "success", "message": "Todo deleted successfully!"}), 200

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500
   
# TO UPDATE DATA

@app.route('/todo/<string:todo_id>', methods=['PUT'])
def update_todo(todo_id):

    request_data = request.get_json()
        
    if not request_data:
        return jsonify({"status":"error", "message":"NO data provided"}) 

    try:

        update_todo = {'$set':{'Title':request_data.get('title'), 'Description':request_data.get('desc')}}     #$set - It is an operator. It sets the value 

        result = mycol.update_one({'_id':ObjectId(todo_id)}, update_todo)

        return jsonify({"status": "success", "message": "Todo updated successfully!"}), 200
    
    except Exception as e:
            return jsonify({"status": "error", "message": str(e)}), 500
    

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)